name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 17 * * 5'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

env:
  GFORTRAN_VERSION: 12
  MATLAB_RELEASE: latest

jobs:
  build:
    name: Install and test MatCUTEst
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        sif: [optrove, zaikun, test]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clone PRIMA
        uses: actions/checkout@v3
        with:
          repository: libprima/prima
          path: prima

      - name: Install 7z
        run: sudo apt install p7zip-full

      - name: Link gfortran for MATLAB on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: bash .github/scripts/link_gfortran ${{ env.GFORTRAN_VERSION }}

      - name: install epstopdf and ghostscript
        if: startsWith(matrix.os, 'ubuntu')
        run: bash .github/scripts/install_epstopdf && bash .github/scripts/install_ghostscript

      - name: Check MATLAB
        id: check_matlab
        run: if type 'matlab' &> /dev/null ; then echo "::set-output name=has_matlab::true" ; fi

      - name: Set up MATLAB
        if: ${{ steps.check_matlab.outputs.has_matlab != 'true' }}
        uses: matlab-actions/setup-matlab@v1.2.4
        with:
          release: ${{ env.MATLAB_RELEASE }}

      - name: Install MatCUTEst
        run: |
          sed 's|matlab -batch.*$|printf "Skip the mexification for GitHub Actions.\\n"|g' -i ./INSTALL
          sed 's|rm -rf.*|printf "Skip removing files for GitHub Actions.\\n"|g' -i ./INSTALL
          OPTROVE_SIF_REPO="https://bitbucket.org/optrove/sif"
          ZAIKUN_SIF_REPO="https://github.com/zaikunzhang/my_cutest_sif.git"
          TEST_SIF_REPO="https://github.com/zaikunzhang/sif_test.git"
          if [[ "${{ matrix.sif }}" = "zaikun" ]] ; then
              sed "s|$OPTROVE_SIF_REPO|$ZAIKUN_SIF_REPO|g" -i ./INSTALL
          elif [[ "${{ matrix.sif }}" = "optrove" ]] ; then
              sed "s|$ZAIKUN_SIF_REPO|$OPTROVE_SIF_REPO|g" -i ./INSTALL
          elif [[ "${{ matrix.sif }}" = "test" ]] ; then
              sed "s|$OPTROVE_SIF_REPO|$TEST_SIF_REPO|g" -i ./INSTALL
              sed "s|$ZAIKUN_SIF_REPO|$TEST_SIF_REPO|g" -i ./INSTALL
          fi
          bash ./INSTALL < install_matcutest_input.pc64.lnx

      - name: Mexify matcutest
        uses: matlab-actions/run-command@v1.1.2
        with:
          command: |
            ver;

            root_dir = cd()
            cd(fullfile(root_dir, 'mtools')); setup;

            cd(getenv('HOME'));
            help matcutest
            which macup

            copyfile(fullfile(root_dir, 'cutest', 'probinfo', 'problist'), fullfile(root_dir, 'problist.${{ matrix.sif }}'));

      - name: Test matcutest
        uses: matlab-actions/run-command@v1.1.2
        with:
          command: |
            ver;
            root_dir = cd()

            cd(fullfile(root_dir, 'mtools')); setup path;

            cd(getenv('HOME'));
            help matcutest
            which macup

            %req = []; req.maxdim=20000; req.maxcon=40000; badlist = chcup(secup(req), 1, 500)
            %if ~isempty(badlist)
            %    error('Some problems did not pass the checking.');
            %end
            %
            %cd(fullfile(root_dir, 'prima', 'matlab', 'tests'));
            %opt.blacklist = {};
            %profile('uobyqa', 'small', 'seq', opt);
            %profile('newuoa', 'small', 'seq', opt);
            %profile('bobyqa', 'small', 'seq', 'b', opt);
            %profile('lincoa', 'small', 'seq', 'l', opt);
            %profile('cobyla', 'small', 'seq', 'n', opt);
            %mkdir(fullfile(root_dir, 'matcutest.${{ matrix. sif}}'));
            %copyfile('./testdata/*summary*.pdf', fullfile(root_dir, 'matcutest.${{ matrix.sif }}'));
            %copyfile('./testdata/*problems.txt', fullfile(root_dir, 'matcutest.${{ matrix.sif }}'));

      - name: Generate matcutest_compiled
        run: |
          sed 's|rm -rf.*|printf "Skip removing files for GitHub Actions.\\n"|g' -i ./extract_mex
          sed 's|.*git\s*clone.*|printf "Skip gitting for GitHub Actions.\\n"|g' -i ./extract_mex
          sed 's|.*git\s*add.*|printf "Skip gitting for GitHub Actions.\\n"|g' -i ./extract_mex
          bash ./extract_mex
          cp matcutest.7z matcutest.${{ matrix.sif }}.7z

      - name: Uninstall MatCUTEst
        run: rm -rf cutest mtools matcutestrc

      - name: Install matcutest_compiled
        run: DIR=$HOME/local && mkdir -p $DIR && mv matcutest.7z $DIR && cd $DIR && 7z x matcutest.7z

      - name: Test matcutest_compiled
        uses: matlab-actions/run-command@v1.1.2
        with:
          command: |
            ver;
            root_dir = cd()
            home_dir = getenv('HOME');

            cd(fullfile(home_dir, 'local', 'matcutest', 'mtools')); setup;

            cd(home_dir)
            help matcutest
            which macup

            req = []; req.maxdim=20000; req.maxcon=40000; badlist = chcup(secup(req), 1, 500)
            if ~isempty(badlist)
                error('Some problems did not pass the checking.');
            end

            cd(fullfile(root_dir, 'prima', 'matlab', 'tests'));
            opt.blacklist = {};
            profile('uobyqa', 'small', 'seq', opt);
            profile('newuoa', 'small', 'seq', opt);
            profile('bobyqa', 'small', 'seq', 'b', opt);
            profile('lincoa', 'small', 'seq', 'l', opt);
            profile('cobyla', 'small', 'seq', 'n', opt);
            mkdir(fullfile(root_dir, 'matcutest.compiled.${{ matrix.sif }}'));
            copyfile('./testdata/*summary*.pdf', fullfile(root_dir, 'matcutest.compiled.${{ matrix.sif }}'));
            copyfile('./testdata/*problems.txt', fullfile(root_dir, 'matcutest.compiled.${{ matrix.sif }}'));

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            matcutest.*
            problist.${{ matrix.sif }}
